### ISSUE TITLE
How to compile/Where to download

### ISSUE THREAD

**Issue by werethless12** [Jupisoft111/Minecraft-Tools#2]
I can't find a download for the main program, or instructions on how to compile.

**Comment by Jupisoft111** [comment]
Hello dear werethless12, I've just downloaded the main code by clicking on the green "Clone or download" button under the page "https://github.com/Jupisoft111/Minecraft-Tools" (at it's right). Then click "Download ZIP", and once the file is downloaded, extract it's contents anywhere in your PC, then navigate in that order to find the pre-compiled executable (which is actually included): "...\Minecraft-Tools-master\Minecraft-Tools-master\Minecraft Tools\bin\Debug\Minecraft Tools.exe".

The folder named "Debug" is the one you need to execute the whole program every time, so you could rename it how you like and move it anywhere, just ignoring the rest of the zip file, the program doesn't need to be installed, just delete it's folder and it will be gone forever, and as long as it's required libraries (.dll files and some others) are near the main executable it should work fine on any place. Although keep in mind that the .exe is made in theory for 64 bits systems. But it can be recompiled to work under 32 bits systems at the cost of only having up to 4 GB or RAM memory for Minecraft worlds loading, which might not always be enough in some cases. To change it to 32 bits click on Visual Studio on the Project properties page, then on the Build tab and check the "Prefer 32 bits" option, finally recompile it (you'll always find the compiled versions on the same path as stated above, in the "Debug" folder).

And to compile it, you'll need to install a version of Microsoft Visual Studio (I'm using 2017, but 2019 is already released, and they are free) for the language C# (check that option in it's installer), then and with Visual Studio already installed, navigate inside the extracted contents of the previously mentioned zip file and double click on this project file: "...\Minecraft-Tools-master\Minecraft-Tools-master\Minecraft Tools.sln". If all was done right, the project should load on Visual Studio, then simply press Control+F5 to start without debugging or go to it's menu and recompile it there. Although I remember you that I just verified that the pre-compiled executable was in it's place and it worked properly, so after I downloaded all it to test it, it worked as expected, at least for me.

![2019_08_22_06_26_34_140](https://user-images.githubusercontent.com/28818179/63485976-ced19380-c4a5-11e9-9296-df9dd8823272.png)

I hope that this might help to clarify everything, but if you still have any other question, let me know and I'll try to help as soon as possible (I can only connect to the internet once a week from my cousin's house, since in my town there isn't internet yet). Sorry if it wasn't clear how to find or compile the included executable, and thanks a lot for asking. Have a nice day.
